### PR TITLE
Add Object#stub_remove_const

### PR DESCRIPTION
**Pull request by sometimesfood**
This commit adds a simple `Object#stub_remove_const` method that removes a constant for the duration of a block. This is quite useful when testing code that checks whether a constant is defined or not.

It would probably be a good idea to merge the unit tests into a single file with nested `describe`s, but I did not want to clutter this pull request too much. If you are interested in merging this, please let me know and I will add another commit to this branch.

### CODE REVIEW

**Comment by adammck** [comment]
Looks good to me, thanks! I agree that it would be clearer to combining the tests into a single file -- would you mind fixing that before I merge?

**Comment by sometimesfood** [comment]
Great to hear that. Sure, I'll just push to this branch when I'm done.

**Comment by sometimesfood** [comment]
I hope the style changes (double quotes vs. single quotes) are ok with you. If not, just give me a shout and I'll change my tests to match your style.

**Comment by adammck** [comment]
Great, thanks! The style changes are fine. Merging, and I'll try to update the gem later today.

**Comment by adammck** [comment]
FYI, [version 0.4](https://rubygems.org/gems/minitest-stub-const/versions/0.4) includes this patch.

**Comment by sometimesfood** [comment]
Great, thanks a lot! Btw, very impressive response time. :smiley:

**Pull request merged**
